### ISSUE TITLE
Every drive deserves an onEnd callback

### ISSUE THREAD

**Issue by dracupid** [ysmood/nokit#3]
Is it a good idea to let every drive has a onEnd callback, not only writers. For instance, what if I want to count lines of code? Or is there another way to achieve this?
```
countLine = ->
    total = 0
    kit._.assign ->
        total += @contents.split('\n').length
    , onEnd: ->
        console.log "Total:  #{total} lines。"
```

**Comment by ysmood** [comment]
```coffee
counter = ->
  count = 0
  {
    drive: -> count++
    report: -> console.log count
  }

c = counter()

kit.warp '*.js'
.load c.drive
.run('dist')
.then ->
   c.report()
```

You need to think things from another aspect. May be the user want to control the report by themselves.

**Comment by dracupid** [comment]
Yes, this is a solution for this example, which is similar with what I'm using now. However, in comparison with Stream, a Transform can always know the end of the stream. 
Hmm.., I can't put forward a more powerful use case for `no` yet. Closure and `then` create more possibilities.

**Comment by ysmood** [comment]
I've 3 lines of code. You can pull it and try it yourself first, if everything is OK, I may add it to the next version.

**Comment by dracupid** [comment]
Passed. Well done!
